services:
  postgres:
    image: postgres:16
    container_name: postgresHost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: grid
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-app:
    build:
      context: FibonacciGridApplication
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  frontend-app:
    build:
      context: fibonacci-grid-frontend
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    driver: local
